apiVersion: v1
kind: Pod
metadata:
  name: jenkins-agent #java-maven
  namespace: jenkins
spec:
  containers:
    - name: jnlp
      image: jenkins/jnlp-agent-maven:latest
      imagePullPolicy: IfNotPresent
      # command:
      #   - sleep
      args:
        - "${computer.jnlpmac}"
        - "${computer.name}"
      resources:
        limits:
          cpu: 100m
          memory: 512Mi
        requests:
          cpu: 100m
          memory: 512Mi   
  imagePullSecrets:
    - name: jenkins-cluster-admin
