apiVersion: v1
kind: PersistentVolume
metadata:
  name: jenkins-pv-volume
  namespace: jenkins
spec:
  storageClassName: "" # managed-premium
  capacity:
    storage: 5Gi # Change<F4><F4><F4> Me
  accessModes:
    - ReadWriteOnce
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: jenkins-pv-claim
    namespace: jenkins
  gcePersistentDisk:
    fsType: ext4
    pdName: data-vol
  persistentVolumeReclaimPolicy: Delete
