apiVersion: v1
kind: PersistentVolume
metadata:
  name: jenkins-pv-volume
  namespace: jenkins
  labels:
    usage: jenkins-shared-deployement
spec:
  storageClassName: standard # managed-premium
  capacity:
    storage: 5Gi # Change<F4><F4><F4> Me
  accessModes:
    - ReadWriteOnce
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: pvc-demo
  gcePersistentDisk:
    fsType: ext4
    pdName: gke-cluster-1-default-pool-5895d0eb-6pgl
  persistentVolumeReclaimPolicy: Delete
  storageClassName: standard
  volumeMode: Filesystem
  hostPath:
    path: "/var/jenkins_home"
