apiVersion: v1
kind: PersistentVolume
metadata:
  name: jenkins-pv-volume
  namespace: jenkins
spec:
  storageClassName: "" #standard # managed-premium
  capacity:
    storage: 5Gi # Change<F4><F4><F4> Me
  accessModes:
    - ReadWriteOnce
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: pvc-demo #jenkins-pvc-claim
    namespace: jenkins
  gcePersistentDisk:
    fsType: ext4
    pdName: data-vol #gke-jenkins-cluster-default-pool-5a13b2fd-d2s5
  persistentVolumeReclaimPolicy: Delete
