---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: jenkins-cluster-admin
  namespace: jenkins
rules:
  - apiGroups: [""]
    resources: ["*"]
    verbs: ["*"]

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: jenkins-cluster-admin
  namespace: jenkins

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: jenkins-cluster-admin
  namespace: jenkins
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: jenkins-cluster-admin
subjects:
- kind: ServiceAccount
  name: jenkins-cluster-admin
  namespace: jenkins
